<?php

return [

    'notationDelimiter' => '',
    'throwErrorOnFailure' => false,

    'isTrue' => [1, '1', 'y', 'on', 'yes', 't', 'true', true],
    'isFalse' => [0, '0', 'n', 'off', 'no', 'f', 'false', false],

    'errorMsg' => '%s is not valid.',

    'ruleDelimiter' => '|',
    'optionLeftDelimiter' => '[',
    'optionRightDelimiter' => ']',
    'defaultOptionDelimiter' => ',',

    'rules' => [
        'allowempty' => \peels\validate\Rules::class . '::allowEmpty',
        'isrequired' => \peels\validate\Rules::class . '::isRequired',

        'isalpha' => \peels\validate\Rules::class . '::isAlpha',
        'isalphadash' => \peels\validate\Rules::class . '::isAlphaDash',
        'isalphanumeric' => \peels\validate\Rules::class . '::isAlphaNumeric',
        'isalphanumericdash' => \peels\validate\Rules::class . '::isAlphaNumericDash',
        'isalphanumericspace' => \peels\validate\Rules::class . '::isAlphaNumericSpace',
        'isalphaspace' => \peels\validate\Rules::class . '::isAlphaSpace',
        'isarray' => \peels\validate\Rules::class . '::isArray',
        'isbool' => \peels\validate\Rules::class . '::isBool',
        'isclass' => \peels\validate\Rules::class . '::isClass',
        'isdecimal' => \peels\validate\Rules::class . '::isDecimal',
        'isexactlength' => \peels\validate\Rules::class . '::isExactLength',
        'isfloat' => \peels\validate\Rules::class . '::isFloat',
        'isgreaterthan' => \peels\validate\Rules::class . '::isGreaterThan',
        'isgreaterthanequalto' => \peels\validate\Rules::class . '::isGreaterThanEqualTo',
        'ishex' => \peels\validate\Rules::class . '::isHex',
        'isinteger' => \peels\validate\Rules::class . '::isInteger',
        'islessthan' => \peels\validate\Rules::class . '::isLessThan',
        'islessthanequalto' => \peels\validate\Rules::class . '::isLessThanEqualTo',
        'islowercase' => \peels\validate\Rules::class . '::isLowercase',
        'isnatural' => \peels\validate\Rules::class . '::isNatural',
        'isnaturalnozero' => \peels\validate\Rules::class . '::isNaturalNoZero',
        'isnumeric' => \peels\validate\Rules::class . '::isNumeric',
        'isoneof' => \peels\validate\Rules::class . '::isOneOf',
        'isregexmatch' => \peels\validate\Rules::class . '::isRegexMatch',
        'isscalar' => \peels\validate\Rules::class . '::isScalar',
        'isstdclass' => \peels\validate\Rules::class . '::isStdClass',
        'isstring' => \peels\validate\Rules::class . '::isString',
        'isuppercase' => \peels\validate\Rules::class . '::isUppercase',
        'isvalidbase64' => \peels\validate\Rules::class . '::isValidBase64',
        'isvaliddate' => \peels\validate\Rules::class . '::isValidDate',
        'isvalidemail' => \peels\validate\Rules::class . '::isValidEmail',
        'isvalidemails' => \peels\validate\Rules::class . '::isValidEmails',
        'isvalidip' => \peels\validate\Rules::class . '::isValidIP',
        'isvalidjson' => \peels\validate\Rules::class . '::isValidJson',
        'isvalidtimezone' => \peels\validate\Rules::class . '::isValidTimezone',
        'isvalidurl' => \peels\validate\Rules::class . '::isValidURL',
        'isvaliduuid' => \peels\validate\Rules::class . '::isValidUuid',

        'convertdate' => \peels\validate\Rules::class . '::convertDate',
        'differs' => \peels\validate\Rules::class . '::differs',
        'filename' => \peels\validate\Rules::class . '::filename',
        'human' => \peels\validate\Rules::class . '::human',
        'input' => \peels\validate\Rules::class . '::input',
        'integer' => \peels\validate\Rules::class . '::integer',
        'length' => \peels\validate\Rules::class . '::length',
        'map' => \peels\validate\Rules::class . '::map',
        'matches' => \peels\validate\Rules::class . '::matches',
        'maxlength' => \peels\validate\Rules::class . '::maxLength',
        'minlength' => \peels\validate\Rules::class . '::minLength',
        'number' => \peels\validate\Rules::class . '::number',
        'readable' => \peels\validate\Rules::class . '::readable',
        'slug' => \peels\validate\Rules::class . '::slug',
        'str' => \peels\validate\Rules::class . '::str',
        'strtolower' => \peels\validate\Rules::class . '::strToLower',
        'strtoupper' => \peels\validate\Rules::class . '::strToUpper',
        'textarea' => \peels\validate\Rules::class . '::textarea',
        'trim' => \peels\validate\Rules::class . '::trim',
        'visible' => \peels\validate\Rules::class . '::visible',
    ],
];
